export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';
export const GENERAL_ERROR_MESSAGE = 'GENERAL_ERROR_MESSAGE';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const GOOGLE_LOGIN_USER = 'GOOGLE_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const UPDATE_SUCCESS_USER = 'UPDATE_SUCCESS_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const IS_WAITING = 'IS_WAITING';
export const IS_NOT_WAITING = 'IS_NOT_WAITING';
export const PROPOSE_TRADE = 'PROPOSE_TRADE';

export const ADD_BOOKS = 'ADD_BOOKS';
export const ADD_BOOK = 'ADD_BOOK';
export const DISPLAY_BOOK_SEARCH = 'DISPLAY_BOOK_SEARCH';
export const ADD_SELECTED_BOOK = 'ADD_SELECTED_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
